mysql:
  image: mysql:5.6
  env_file: parameters.env
  volumes:
    - "./data/mysql:/var/lib/mysql"

rabbitmq:
  image: rabbitmq:latest
  volumes:
    - "./data/rabbitmq:/var/lib/rabbitmq"

redis:
  image: redis:latest
  volumes:
    - "./data/redis:/var/lib/redis"

dispatcher:
  image: simpleci/dispatcher
  links:
    - mysql:mysql
    - redis:redis
  env_file: parameters.env

worker:
  image: simpleci/worker
  links:
    - rabbitmq:rabbitmq
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  env_file: parameters.env

frontend:
  image: simpleci/frontend
  links:
    - mysql:mysql
    - redis:redis
  ports:
   - "8082:80"
  volumes:
    - "./log/frontend:/var/log/simpleci"
    - "./log/frontend/app:/home/simpleci/frontend/app/logs"
  env_file: parameters.env
