mysql:
  image: mysql:5.6
  env_file: parameters.env
  volumes:
    - "./data/mysql:/var/lib/mysql"

rabbitmq:
  image: rabbitmq:latest
  volumes:
    - "./data/rabbitmq:/var/lib/rabbitmq"

redis:
  image: redis:latest
  volumes:
    - "./data/redis:/var/lib/redis"

worker:
  image: quay.io/simpleci/worker:latest
  links:
    - rabbitmq:rabbitmq
  volumes:
    - "./log/worker:/var/log/simpleci"
    - "./data/worker/cache:/home/simpleci/worker/app/cache"
    - "/var/run/docker.sock:/var/run/docker.sock"
  env_file: parameters.env

frontend:
  image: quay.io/simpleci/frontend:latest
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
  ports:
   - "8082:80"
  volumes:
    - "./log/frontend:/var/log/simpleci"
    - "./log/frontend/app:/home/simpleci/frontend/app/logs"
  env_file: parameters.env


