mysql:
  image: mysql:5.6
  env_file: parameters.env
  volumes:
    - "/opt/simpleci/data/mysql:/var/lib/mysql"

rabbitmq:
  image: rabbitmq:latest
  volumes:
    - "/opt/simpleci/data/rabbitmq:/var/lib/rabbitmq"

redis:
  image: redis:latest
  volumes:
    - "/opt/simpleci/data/redis:/var/lib/redis"

centrifugo:
  image: quay.io/simpleci/centrifugo:1.1.0
  links:
    - redis:redis
  env_file: parameters.env

dispatcher:
  image: quay.io/simpleci/dispatcher:0.1.0
  links:
    - redis:redis
    - rabbitmq:rabbitmq
    - mysql:mysql
  volumes:
    - "/opt/simpleci/log:/var/log/simpleci"
  env_file: parameters.env

worker:
  image: quay.io/simpleci/worker:0.1.1
  links:
    - rabbitmq:rabbitmq
  volumes:
    - "/opt/simpleci/log:/var/log/simpleci"
    - "/opt/simpleci/data/worker/cache:/home/simpleci/worker/app/cache"
    - "/var/run/docker.sock:/var/run/docker.sock"
  env_file: parameters.env

frontend:
  image: quay.io/simpleci/frontend:0.1.0
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
    - centrifugo:centrifugo
  ports:
   - "8082:80"
  volumes:
    - "/opt/simpleci/log:/var/log/simpleci"
  env_file: parameters.env


